#!/bin/bash

PYTHON=${PYTHON-python}

MESOS_BUILD_DIR=${MESOS_BUILD_DIR-`dirname $0`/../..}

PROTOBUF_EGG_PATH='third_party/protobuf-*/python/dist/protobbuf*.egg'
PROTOBUF_EGG=${PROTOBUF_EGG-`echo ${MESOS_BUILD_DIR}/${PROTOBUF_EGG_PATH}`}

MESOS_EGG=${MESOS_EGG-`echo ${MESOS_BUILD_DIR}/src/python/dist/mesos*.egg`}

export PYTHONPATH=$MESOS_EGG:$PROTOBUF_EGG:$PYTHONPATH

exec $PYTHON ./haproxy+apache.py "${@}"
